# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2020-05-05 00:12:21
"""
import arcpy
from sys import argv

def Model1(Input_Rasters, Landsat_Raster_Band_10, Landsat_Raster_Band_4, Landsat_Raster_Band_1, Landsat_Raster_Band_5, Landsat_Raster_Band_3, Landsat_Raster_Band_7, Output_Composite, NDVI_Output="C:\\Users\\jf_ph\\OneDrive\\Documentos\\ArcGIS\\Projects\\MyProject\\MyProject.gdb\\rastercalc12_Clip_CopyRaster", Surface_Albedo_Raster="C:\\Users\\jf_ph\\OneDrive\\Documentos\\ArcGIS\\Projects\\MyProject\\MyProject.gdb\\rastercalc11__Clip_CopyRaste", Emissivity_Raster="C:\\Users\\jf_ph\\OneDrive\\Documentos\\ArcGIS\\Projects\\MyProject\\MyProject.gdb\\rastercal_444_Clip_CopyRaste", Surface_Temperature_Output="C:\\Users\\jf_ph\\OneDrive\\Documentos\\ArcGIS\\Projects\\UCDavisProject\\UCDavisProject.gdb\\c1_rastercal_CopyRaster"):  # GEEModeling

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("ImageAnalyst")


    # Process: Composite Bands (Composite Bands) 
    Composite_Raster = ""
    arcpy.CompositeBands_management(in_rasters=Input_Rasters, out_raster=Composite_Raster)

    # Process: Copy Raster (2) (Copy Raster) 
    arcpy.CopyRaster_management(in_raster=Composite_Raster, out_rasterdataset=Output_Composite, config_keyword="", background_value=None, nodata_value="", onebit_to_eightbit="NONE", colormap_to_RGB="NONE", pixel_type="", scale_pixel_value="NONE", RGB_to_Colormap="NONE", format="", transform="NONE", process_as_multidimensional="CURRENT_SLICE", build_multidimensional_transpose="NO_TRANSPOSE")

    # Process: Copy Raster (3) (Copy Raster) 
    Output_Raster_Band_5 = ""
    arcpy.CopyRaster_management(in_raster=Landsat_Raster_Band_5, out_rasterdataset=Output_Raster_Band_5, config_keyword="", background_value=None, nodata_value="", onebit_to_eightbit="NONE", colormap_to_RGB="NONE", pixel_type="", scale_pixel_value="NONE", RGB_to_Colormap="NONE", format="", transform="NONE", process_as_multidimensional="CURRENT_SLICE", build_multidimensional_transpose="NO_TRANSPOSE")

    # Process: Copy Raster (7) (Copy Raster) 
    Output_Raster_Band_4 = ""
    arcpy.CopyRaster_management(in_raster=Landsat_Raster_Band_4, out_rasterdataset=Output_Raster_Band_4, config_keyword="", background_value=None, nodata_value="", onebit_to_eightbit="NONE", colormap_to_RGB="NONE", pixel_type="", scale_pixel_value="NONE", RGB_to_Colormap="NONE", format="", transform="NONE", process_as_multidimensional="CURRENT_SLICE", build_multidimensional_transpose="NO_TRANSPOSE")

    # Process: NDVI Calculator (Raster Calculator) 
    NDVI_Raster = "C:\\Users\\jf_ph\\onedrive\\documentos\\arcgis\\projects\\myproject\\myproject.gdb\\rastercalc12"
    arcpy.RasterCalculator_ia(expression=[Output_Raster_Band_5, Output_Raster_Band_4, Output_Raster_Band_5, Output_Raster_Band_4], output_raster=NDVI_Raster)

    # Process: Get Raster Properties (Get Raster Properties) 
    MIN_NDVI = arcpy.GetRasterProperties_management(in_raster=NDVI_Raster, property_type="MINIMUM", band_index="")[0]

    # Process: Get Raster Properties (2) (Get Raster Properties) 
    MAX_NDVI = arcpy.GetRasterProperties_management(in_raster=NDVI_Raster, property_type="MAXIMUM", band_index="")[0]

    # Process: Calculate FCV (Raster Calculator) 
    fcv = "C:\\Users\\jf_ph\\onedrive\\documentos\\arcgis\\projects\\ucdavisproject\\ucdavisproject.gdb\\band_1_raste"
    arcpy.RasterCalculator_ia(expression=[NDVI_Raster, MIN_NDVI, MAX_NDVI, MIN_NDVI], output_raster=fcv)

    # Process: Calculate Emissivity (Raster Calculator) 
    Emissivity = "C:\\Users\\jf_ph\\OneDrive\\Documentos\\ArcGIS\\Projects\\MyProject\\MyProject.gdb\\rastercal_444"
    arcpy.RasterCalculator_ia(expression=[NDVI_Raster, NDVI_Raster, NDVI_Raster, fcv, NDVI_Raster], output_raster=Emissivity)

    # Process: Copy Raster (8) (Copy Raster) 
    arcpy.CopyRaster_management(in_raster=Emissivity, out_rasterdataset=Emissivity_Raster, config_keyword="", background_value=None, nodata_value="", onebit_to_eightbit="NONE", colormap_to_RGB="NONE", pixel_type="", scale_pixel_value="NONE", RGB_to_Colormap="NONE", format="", transform="NONE", process_as_multidimensional="CURRENT_SLICE", build_multidimensional_transpose="NO_TRANSPOSE")

    # Process: Copy Raster (4) (Copy Raster) 
    Output_Raster_Band_1 = ""
    arcpy.CopyRaster_management(in_raster=Landsat_Raster_Band_1, out_rasterdataset=Output_Raster_Band_1, config_keyword="", background_value=None, nodata_value="", onebit_to_eightbit="NONE", colormap_to_RGB="NONE", pixel_type="", scale_pixel_value="NONE", RGB_to_Colormap="NONE", format="", transform="NONE", process_as_multidimensional="CURRENT_SLICE", build_multidimensional_transpose="NO_TRANSPOSE")

    # Process: CONVERT ND 1 TO REFLECTANCE (Raster Calculator) 
    REFL_1 = "C:\\Users\\jf_ph\\onedrive\\documentos\\arcgis\\projects\\myproject\\myproject.gdb\\rastercalc13"
    arcpy.RasterCalculator_ia(expression=[Output_Raster_Band_1], output_raster=REFL_1)

    # Process: CORRECT REFLECTANCE_1 (Raster Calculator) 
    REFLECTANCE_1 = "C:\\Users\\jf_ph\\OneDrive\\documentos\\ArcGIS\\Projects\\myproject\\myproject.gdb\\rastercalc20"
    arcpy.RasterCalculator_ia(expression=[REFL_1], output_raster=REFLECTANCE_1)

    # Process: Copy Raster (5) (Copy Raster) 
    Output_Raster_Band_3 = ""
    arcpy.CopyRaster_management(in_raster=Landsat_Raster_Band_3, out_rasterdataset=Output_Raster_Band_3, config_keyword="", background_value=None, nodata_value="", onebit_to_eightbit="NONE", colormap_to_RGB="NONE", pixel_type="", scale_pixel_value="NONE", RGB_to_Colormap="NONE", format="", transform="NONE", process_as_multidimensional="CURRENT_SLICE", build_multidimensional_transpose="NO_TRANSPOSE")

    # Process: CONVERT ND 3 TO REFLECTANCE (Raster Calculator) 
    REFL_3 = "C:\\Users\\jf_ph\\OneDrive\\documentos\\ArcGIS\\Projects\\myproject\\myproject.gdb\\rastercalc14"
    arcpy.RasterCalculator_ia(expression=[Output_Raster_Band_3], output_raster=REFL_3)

    # Process: CORRECT REFLECTANCE_3 (Raster Calculator) 
    REFLECTANCE_3 = "C:\\Users\\jf_ph\\onedrive\\documentos\\arcgis\\projects\\myproject\\myproject.gdb\\rastercalc11"
    arcpy.RasterCalculator_ia(expression=[REFL_3], output_raster=REFLECTANCE_3)

    # Process: CONVERT ND 4 TO REFLECTANCE (Raster Calculator) 
    REFL_4 = "C:\\Users\\jf_ph\\onedrive\\documentos\\arcgis\\projects\\myproject\\myproject.gdb\\band_1_raste"
    arcpy.RasterCalculator_ia(expression=[Output_Raster_Band_4], output_raster=REFL_4)

    # Process: CORRECT REFLECTANCE_4 (Raster Calculator) 
    REFLECTANCE_4 = "C:\\Users\\jf_ph\\OneDrive\\documentos\\ArcGIS\\Projects\\myproject\\myproject.gdb\\band_1_rastr"
    arcpy.RasterCalculator_ia(expression=[REFL_4], output_raster=REFLECTANCE_4)

    # Process: CONVERT ND 5 TO RELECTANCE (Raster Calculator) 
    REFL_5 = "C:\\Users\\jf_ph\\onedrive\\documentos\\arcgis\\projects\\myproject\\myproject.gdb\\band_1_raste"
    arcpy.RasterCalculator_ia(expression=[Output_Raster_Band_5], output_raster=REFL_5)

    # Process: CORRECT REFLECTANCE_5 (Raster Calculator) 
    REFLECTANCE_5 = "C:\\Users\\jf_ph\\onedrive\\documentos\\arcgis\\projects\\myproject\\myproject.gdb\\band_1_rast1"
    arcpy.RasterCalculator_ia(expression=[REFL_5], output_raster=REFLECTANCE_5)

    # Process: Copy Raster (6) (Copy Raster) 
    Output_Raster_Band_7 = ""
    arcpy.CopyRaster_management(in_raster=Landsat_Raster_Band_7, out_rasterdataset=Output_Raster_Band_7, config_keyword="", background_value=None, nodata_value="", onebit_to_eightbit="NONE", colormap_to_RGB="NONE", pixel_type="", scale_pixel_value="NONE", RGB_to_Colormap="NONE", format="", transform="NONE", process_as_multidimensional="CURRENT_SLICE", build_multidimensional_transpose="NO_TRANSPOSE")

    # Process: CONVERT ND 7 TO REFLECTANCE (Raster Calculator) 
    REFL_7 = "C:\\Users\\jf_ph\\onedrive\\documentos\\arcgis\\projects\\myproject\\myproject.gdb\\rastercalc"
    arcpy.RasterCalculator_ia(expression=[Output_Raster_Band_7], output_raster=REFL_7)

    # Process: CORRECT REFLECTANCE_7 (Raster Calculator) 
    REFLECTANCE_7 = "C:\\Users\\jf_ph\\onedrive\\documentos\\arcgis\\projects\\myproject\\myproject.gdb\\rastercalc_r"
    arcpy.RasterCalculator_ia(expression=[REFL_7], output_raster=REFLECTANCE_7)

    # Process: CALCULATE ALBEDO (Raster Calculator) 
    ALBEDO = "C:\\Users\\jf_ph\\OneDrive\\documentos\\ArcGIS\\Projects\\myproject\\myproject.gdb\\rastercalc11_"
    arcpy.RasterCalculator_ia(expression=[REFLECTANCE_1, REFLECTANCE_3, REFLECTANCE_4, REFLECTANCE_5, REFLECTANCE_7], output_raster=ALBEDO)

    # Process: Copy Raster (9) (Copy Raster) 
    arcpy.CopyRaster_management(in_raster=ALBEDO, out_rasterdataset=Surface_Albedo_Raster, config_keyword="", background_value=None, nodata_value="", onebit_to_eightbit="NONE", colormap_to_RGB="NONE", pixel_type="", scale_pixel_value="NONE", RGB_to_Colormap="NONE", format="", transform="NONE", process_as_multidimensional="CURRENT_SLICE", build_multidimensional_transpose="NO_TRANSPOSE")

    # Process: Copy Raster (11) (Copy Raster) 
    arcpy.CopyRaster_management(in_raster=NDVI_Raster, out_rasterdataset=NDVI_Output, config_keyword="", background_value=None, nodata_value="", onebit_to_eightbit="NONE", colormap_to_RGB="NONE", pixel_type="", scale_pixel_value="NONE", RGB_to_Colormap="NONE", format="", transform="NONE", process_as_multidimensional="CURRENT_SLICE", build_multidimensional_transpose="NO_TRANSPOSE")

    # Process: Copy Raster (Copy Raster) 
    Output_Raster_Band_10 = ""
    arcpy.CopyRaster_management(in_raster=Landsat_Raster_Band_10, out_rasterdataset=Output_Raster_Band_10, config_keyword="", background_value=None, nodata_value="", onebit_to_eightbit="NONE", colormap_to_RGB="NONE", pixel_type="", scale_pixel_value="NONE", RGB_to_Colormap="NONE", format="", transform="NONE", process_as_multidimensional="CURRENT_SLICE", build_multidimensional_transpose="NO_TRANSPOSE")

    # Process: CONVERT ND 10 TO RADIANCE (Raster Calculator) 
    RADIANCE_BAND_10 = "C:\\Users\\jf_ph\\onedrive\\documentos\\arcgis\\projects\\ucdavisproject\\ucdavisproject.gdb\\rastercalc"
    arcpy.RasterCalculator_ia(expression=[Output_Raster_Band_10], output_raster=RADIANCE_BAND_10)

    # Process: CALCULATE ST (Raster Calculator) 
    ST = "C:\\Users\\jf_ph\\onedrive\\documentos\\arcgis\\projects\\myproject\\myproject.gdb\\rastercalc1_"
    arcpy.RasterCalculator_ia(expression=[RADIANCE_BAND_10], output_raster=ST)

    # Process: Copy Raster (10) (Copy Raster) 
    Surface_Temperature_Raster = "C:\\Users\\jf_ph\\OneDrive\\Documentos\\ArcGIS\\Projects\\MyProject\\MyProject.gdb\\rastercalc1__Clip_CopyRaster"
    arcpy.CopyRaster_management(in_raster=ST, out_rasterdataset=Surface_Temperature_Raster, config_keyword="", background_value=None, nodata_value="", onebit_to_eightbit="NONE", colormap_to_RGB="NONE", pixel_type="", scale_pixel_value="NONE", RGB_to_Colormap="NONE", format="", transform="NONE", process_as_multidimensional="CURRENT_SLICE", build_multidimensional_transpose="NO_TRANSPOSE")

    # Process: Raster Calculator (Raster Calculator) 
    Surface_Temperature = "C:\\Users\\jf_ph\\onedrive\\documentos\\arcgis\\projects\\ucdavisproject\\ucdavisproject.gdb\\c1_rastercal"
    arcpy.RasterCalculator_ia(expression=[Surface_Temperature_Raster, Surface_Temperature_Raster, Emissivity], output_raster=Surface_Temperature)

    # Process: Copy Raster (12) (Copy Raster) 
    arcpy.CopyRaster_management(in_raster=Surface_Temperature, out_rasterdataset=Surface_Temperature_Output, config_keyword="", background_value=None, nodata_value="", onebit_to_eightbit="NONE", colormap_to_RGB="NONE", pixel_type="", scale_pixel_value="NONE", RGB_to_Colormap="NONE", format="", transform="NONE", process_as_multidimensional="CURRENT_SLICE", build_multidimensional_transpose="NO_TRANSPOSE")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\jf_ph\OneDrive\Documentos\ArcGIS\Projects\UCDavisProject\UCDavisProject.gdb", workspace=r"C:\Users\jf_ph\OneDrive\Documentos\ArcGIS\Projects\UCDavisProject\UCDavisProject.gdb"):
        Model1(*argv[1:])
